#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys,os,subprocess

try:
    import yaml
    import parted
    import pytz
    from PyQt5.QtCore import Qt
    from PyQt5.QtWidgets import QMainWindow, QSplitter,QWidget, QHBoxLayout, QStackedWidget, QPushButton, QApplication
    from PyQt5.QtGui import QIcon
except ImportError as e:
    print("{}\n import işlemi sırasında hata oluştu".format(e))

from lib import miliskurqrc
from lib.ui import hosgeldinizui, kontrolui, kullaniciui, bolumlemeui, grubui, kurulumui, bitisui, saatdilimiui

class MilisMerkezPencere(QMainWindow):
    def __init__(self, ebeveyn=None):
        super(MilisMerkezPencere, self).__init__(ebeveyn)
        self.setWindowIcon(QIcon(":/slaytlar/icon.svg"))

        ###################################
        ##      Kurulum Değişkenleri     ##
        ###################################
        self.kurulum_dosya = "/opt/kurulum.yml"
        self.kurparam = None
        self.disk = None
        self.sistemDili = None

        #Milis Yükleyici Temel Görünümünü Ayarlıyoruz
        anaAyirici = QSplitter(Qt.Vertical)
        self.setCentralWidget(anaAyirici)
        self.setFixedWidth(800)
        self.setFixedHeight(500)
        self.ustParca = QWidget()
        altAyirici = QSplitter(Qt.Vertical)
        anaAyirici.addWidget(self.ustParca)
        anaAyirici.addWidget(altAyirici)
        yiginParca = QWidget()
        dugmeParca = QWidget()
        altAyirici.addWidget(yiginParca)
        altAyirici.addWidget(dugmeParca)
        self.ustParca.setStyleSheet("background-image: url(:/slaytlar/merkezArkaplan_1.png);")
        self.ustParca.setFixedWidth(800)
        self.ustParca.setFixedHeight(125)
        yiginParca.setFixedHeight(325)
        dugmeParca.setFixedHeight(50)

        #Yığınları ayarlıyoruz
        self.yiginNumarasi = 0
        self.sonyigin = 0
        yiginKutusu = QHBoxLayout()
        yiginParca.setLayout(yiginKutusu)
        self.yiginWidget = QStackedWidget()
        yiginKutusu.addWidget(self.yiginWidget)
        self.yiginWidget.addWidget(hosgeldinizui.HosgeldinizPencere(self))
        self.yiginWidget.addWidget(kontrolui.KontrolPencere(self))
        self.saatDilimiPencere = saatdilimiui.SaatDilimiPencere(self)
        self.yiginWidget.addWidget(self.saatDilimiPencere)
        self.yiginWidget.addWidget(kullaniciui.KullaniciPencere(self))
        self.yiginWidget.addWidget(bolumlemeui.BolumlemePencere(self))
        self.yiginWidget.addWidget(grubui.GrubPencere(self))
        self.yiginWidget.addWidget(kurulumui.KurulumPencere(self))
        self.yiginWidget.addWidget(bitisui.BitisPencere(self))

        dugmeKutusu = QHBoxLayout()
        dugmeParca.setLayout(dugmeKutusu)
        self.geriDugme = QPushButton(self.tr("geri"))
        self.geriDugme.setDisabled(True)
        self.geriDugme.clicked.connect(self.geriDugmeFonksiyon)
        self.ileriDugme = QPushButton(self.tr("ileri"))
        self.ileriDugme.setDisabled(True)
        self.ileriDugme.clicked.connect(self.ileriDugmeFonksiyon)
        dugmeKutusu.addWidget(self.geriDugme)
        dugmeKutusu.addWidget(self.ileriDugme)


    def ileriDugmeFonksiyon(self):
        self.yiginNumarasi += 1
        if self.yiginNumarasi != 0:
            self.geriDugme.setDisabled(False)
        if self.sonyigin < self.yiginNumarasi:
            self.sonyigin += 1
            self.ileriDugme.setDisabled(True)
        elif self.sonyigin == self.yiginNumarasi:
            self.ileriDugme.setDisabled(True)
        if self.yiginNumarasi == 2:
            self.saatDilimiPencere.sehirlerCombo.setCurrentText("Istanbul")
        self.ustParcaGuncelle(str(self.yiginNumarasi + 1))
        self.yiginWidget.setCurrentIndex(self.yiginNumarasi)

    def geriDugmeFonksiyon(self):
        self.yiginNumarasi -= 1
        if self.yiginNumarasi == 0:
            self.geriDugme.setDisabled(True)
        if self.sonyigin > self.yiginNumarasi:
            self.ileriDugme.setDisabled(False)
        self.ustParcaGuncelle(str(self.yiginNumarasi + 1))
        self.yiginWidget.setCurrentIndex(self.yiginNumarasi)

    def komutCalistirFonksiyon(self, komut):
        try:
            out = subprocess.check_output(komut, stderr=subprocess.STDOUT, shell=True, universal_newlines=True)
            return out.replace("\b", "")
        except subprocess.CalledProcessError as e:
            return e.output

    def kurulum_oku(self, kurulumdos):
        with open(kurulumdos, 'r') as f:
            param = yaml.load(f)
        self.kurparam = param
        return param

    def kurulum_yaz(self, param, kurulumdos):
        with open(kurulumdos, 'w') as outfile:
            yaml.dump(param, outfile, default_flow_style=False, allow_unicode=True)

    def ustParcaGuncelle(self, numara):
        self.ustParca.setStyleSheet("background-image: url(:/slaytlar/merkezArkaplan_" + numara + ".png);")


if __name__ == "__main__":
    if os.getuid() != 0:
        print("Hata\n","Lütfen Milis-Kuru Root olarak çalıştırınız")
    else:
        yol=os.getcwd()
        uygulama = QApplication(sys.argv)
        uygulama.setOrganizationName('Milis Linux')
        uygulama.setApplicationName('Milis Yukleyici')
        merkezPencere = MilisMerkezPencere()
        merkezPencere.show()
        sys.exit(uygulama.exec_())
